name: Build Windows
on:
  workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: 'x64'
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30'
      - name: Configure
        run: cmake -B Build -G "Visual Studio 17 2022" -A x64
      - name: Build
        run: |
          msbuild Build/ALL_BUILD.vcxproj -p:Configuration=Release -p:Platform=x64
      - name: Run Tests
        run: |
          cd Build
          ctest -C Release --output-on-failure
          